### ISSUE TITLE
Equipo incompleto

### ISSUE THREAD

**Issue by jorgaf** [dani117m/ProyectoProAvB2#2]
Revisen los miembros del equipo, no creo que están todos. No se olviden de incluir en su proyecto para poder realizar de mejor manera el seguimiento del proyecto.

**Comment by ricardoifc** [comment]
Es de 2 o de 3???

**Comment by jorgaf** [comment]
Son 3 conmigo, que tengo ser parte del proyecto para poder cumplir con mi trabajo en las revisiones del proyecto
